/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resistor_colour_calculator;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class Colour_code_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Colour_code_Calculator
     */
    public Colour_code_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jchkFWhite = new javax.swing.JCheckBox();
        jchkFBlack = new javax.swing.JCheckBox();
        jchkFBrown = new javax.swing.JCheckBox();
        jchkFRed = new javax.swing.JCheckBox();
        jchkFOrange = new javax.swing.JCheckBox();
        jchkFYellow = new javax.swing.JCheckBox();
        jchkFGreen = new javax.swing.JCheckBox();
        jchkFBlue = new javax.swing.JCheckBox();
        jchkFViolet = new javax.swing.JCheckBox();
        jchkFGray = new javax.swing.JCheckBox();
        jchkSWhite = new javax.swing.JCheckBox();
        jchkSGray = new javax.swing.JCheckBox();
        jchkSViolet = new javax.swing.JCheckBox();
        jchkSBlue = new javax.swing.JCheckBox();
        jchkSGreen = new javax.swing.JCheckBox();
        jchkSYellow = new javax.swing.JCheckBox();
        jchkSOrange = new javax.swing.JCheckBox();
        jchkSRed = new javax.swing.JCheckBox();
        jchkSBrown = new javax.swing.JCheckBox();
        jchkSBlack = new javax.swing.JCheckBox();
        jchkMBrown = new javax.swing.JCheckBox();
        jchkMWhite = new javax.swing.JCheckBox();
        jchkMRed = new javax.swing.JCheckBox();
        jchkMOrange = new javax.swing.JCheckBox();
        jchkMGray = new javax.swing.JCheckBox();
        jchkMViolet = new javax.swing.JCheckBox();
        jchkMBlue = new javax.swing.JCheckBox();
        jchkMGreen = new javax.swing.JCheckBox();
        jchkMYellow = new javax.swing.JCheckBox();
        jchkMBlack = new javax.swing.JCheckBox();
        jchkNone = new javax.swing.JCheckBox();
        jchkSliver = new javax.swing.JCheckBox();
        jchkGold = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jlblLine4 = new javax.swing.JLabel();
        jlblLine1 = new javax.swing.JLabel();
        jlblLine2 = new javax.swing.JLabel();
        jlblLine3 = new javax.swing.JLabel();
        jlblIndicator = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jlblSecondColour = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jlblMultiple = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jlblFirstColour = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jlblMinRange = new javax.swing.JLabel();
        jlblResistorValue = new javax.swing.JLabel();
        jlblDivideby1000 = new javax.swing.JLabel();
        jlblMaxRange = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 800));
        setPreferredSize(new java.awt.Dimension(1380, 850));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WHITE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BLACK");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, -1));

        jLabel3.setBackground(new java.awt.Color(204, 51, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BROWN");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, -1));

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RED");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ORANGE");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("YELLOW");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, -1));

        jLabel7.setBackground(new java.awt.Color(51, 204, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GREEN");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, -1));

        jLabel8.setBackground(new java.awt.Color(0, 51, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BLUE");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, -1));

        jLabel9.setBackground(new java.awt.Color(255, 51, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VIOLET");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, -1));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GRAY");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, -1));

        jLabel11.setBackground(new java.awt.Color(255, 204, 153));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("GOLD");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 90, -1));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SLIVER");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 90, -1));

        jLabel13.setBackground(new java.awt.Color(102, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TOLERANCE");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 110, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("9");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 90, -1));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("8");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 90, -1));

        jLabel16.setBackground(new java.awt.Color(255, 51, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("7");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 90, -1));

        jLabel17.setBackground(new java.awt.Color(0, 51, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("6");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setOpaque(true);
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 90, -1));

        jLabel18.setBackground(new java.awt.Color(51, 204, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("5");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setOpaque(true);
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 90, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("4");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setOpaque(true);
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 90, -1));

        jLabel20.setBackground(new java.awt.Color(255, 153, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("3");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setOpaque(true);
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 90, -1));

        jLabel21.setBackground(new java.awt.Color(255, 51, 51));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("2");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setOpaque(true);
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, -1));

        jLabel22.setBackground(new java.awt.Color(204, 51, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("1");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel22.setOpaque(true);
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 90, -1));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("0");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel23.setOpaque(true);
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 90, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("NONE");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel24.setOpaque(true);
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 90, -1));

        jLabel25.setBackground(new java.awt.Color(102, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("COLOUR");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel25.setOpaque(true);
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        jLabel26.setBackground(new java.awt.Color(102, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("NUMBER");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel26.setOpaque(true);
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, -1));

        jLabel27.setBackground(new java.awt.Color(102, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("1st COLOUR");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel27.setOpaque(true);
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 110, -1));

        jLabel28.setBackground(new java.awt.Color(102, 255, 255));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("2nd COLOUR");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel28.setOpaque(true);
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 110, -1));

        jLabel29.setBackground(new java.awt.Color(102, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("MULTIPLIER");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.setOpaque(true);
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 110, -1));

        jchkFWhite.setBackground(new java.awt.Color(255, 255, 255));
        jchkFWhite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFWhite.setBorderPainted(true);
        jchkFWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFWhiteActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 110, 20));

        jchkFBlack.setBackground(new java.awt.Color(0, 0, 0));
        jchkFBlack.setForeground(new java.awt.Color(255, 255, 255));
        jchkFBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFBlack.setBorderPainted(true);
        jchkFBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFBlackActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 110, -1));

        jchkFBrown.setBackground(new java.awt.Color(204, 51, 0));
        jchkFBrown.setForeground(new java.awt.Color(255, 255, 255));
        jchkFBrown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFBrown.setBorderPainted(true);
        jchkFBrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFBrownActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFBrown, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 110, -1));

        jchkFRed.setBackground(new java.awt.Color(255, 51, 51));
        jchkFRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFRed.setBorderPainted(true);
        jchkFRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFRedActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, -1));

        jchkFOrange.setBackground(new java.awt.Color(255, 153, 0));
        jchkFOrange.setForeground(new java.awt.Color(255, 255, 255));
        jchkFOrange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFOrange.setBorderPainted(true);
        jchkFOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFOrangeActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 110, -1));

        jchkFYellow.setBackground(new java.awt.Color(255, 255, 0));
        jchkFYellow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFYellow.setBorderPainted(true);
        jchkFYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFYellowActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 110, -1));

        jchkFGreen.setBackground(new java.awt.Color(51, 204, 0));
        jchkFGreen.setForeground(new java.awt.Color(255, 255, 255));
        jchkFGreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFGreen.setBorderPainted(true);
        jchkFGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFGreenActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 110, 20));

        jchkFBlue.setBackground(new java.awt.Color(0, 51, 204));
        jchkFBlue.setForeground(new java.awt.Color(255, 255, 255));
        jchkFBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFBlue.setBorderPainted(true);
        jchkFBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFBlueActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 110, 20));

        jchkFViolet.setBackground(new java.awt.Color(255, 51, 255));
        jchkFViolet.setForeground(new java.awt.Color(255, 255, 255));
        jchkFViolet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFViolet.setBorderPainted(true);
        jchkFViolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFVioletActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFViolet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 110, 20));

        jchkFGray.setBackground(new java.awt.Color(102, 102, 102));
        jchkFGray.setForeground(new java.awt.Color(255, 255, 255));
        jchkFGray.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkFGray.setBorderPainted(true);
        jchkFGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFGrayActionPerformed(evt);
            }
        });
        jPanel3.add(jchkFGray, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 110, 20));

        jchkSWhite.setBackground(new java.awt.Color(255, 255, 255));
        jchkSWhite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSWhite.setBorderPainted(true);
        jchkSWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSWhiteActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 110, 20));

        jchkSGray.setBackground(new java.awt.Color(102, 102, 102));
        jchkSGray.setForeground(new java.awt.Color(255, 255, 255));
        jchkSGray.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSGray.setBorderPainted(true);
        jchkSGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSGrayActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSGray, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 110, 20));

        jchkSViolet.setBackground(new java.awt.Color(255, 51, 255));
        jchkSViolet.setForeground(new java.awt.Color(255, 255, 255));
        jchkSViolet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSViolet.setBorderPainted(true);
        jchkSViolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSVioletActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSViolet, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 110, 20));

        jchkSBlue.setBackground(new java.awt.Color(0, 51, 204));
        jchkSBlue.setForeground(new java.awt.Color(255, 255, 255));
        jchkSBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSBlue.setBorderPainted(true);
        jchkSBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSBlueActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 110, 20));

        jchkSGreen.setBackground(new java.awt.Color(51, 204, 0));
        jchkSGreen.setForeground(new java.awt.Color(255, 255, 255));
        jchkSGreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSGreen.setBorderPainted(true);
        jchkSGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSGreenActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 110, 20));

        jchkSYellow.setBackground(new java.awt.Color(255, 255, 0));
        jchkSYellow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSYellow.setBorderPainted(true);
        jchkSYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSYellowActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 110, -1));

        jchkSOrange.setBackground(new java.awt.Color(255, 153, 0));
        jchkSOrange.setForeground(new java.awt.Color(255, 255, 255));
        jchkSOrange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSOrange.setBorderPainted(true);
        jchkSOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSOrangeActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 110, -1));

        jchkSRed.setBackground(new java.awt.Color(255, 51, 51));
        jchkSRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSRed.setBorderPainted(true);
        jchkSRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSRedActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 110, -1));

        jchkSBrown.setBackground(new java.awt.Color(204, 51, 0));
        jchkSBrown.setForeground(new java.awt.Color(255, 255, 255));
        jchkSBrown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSBrown.setBorderPainted(true);
        jchkSBrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSBrownActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSBrown, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 110, -1));

        jchkSBlack.setBackground(new java.awt.Color(0, 0, 0));
        jchkSBlack.setForeground(new java.awt.Color(255, 255, 255));
        jchkSBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSBlack.setBorderPainted(true);
        jchkSBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSBlackActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 110, -1));

        jchkMBrown.setBackground(new java.awt.Color(204, 51, 0));
        jchkMBrown.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMBrown.setForeground(new java.awt.Color(255, 255, 255));
        jchkMBrown.setText("10");
        jchkMBrown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMBrown.setBorderPainted(true);
        jchkMBrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMBrownActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMBrown, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 110, -1));

        jchkMWhite.setBackground(new java.awt.Color(255, 255, 255));
        jchkMWhite.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMWhite.setText("1000000000");
        jchkMWhite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMWhite.setBorderPainted(true);
        jchkMWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMWhiteActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 110, 20));

        jchkMRed.setBackground(new java.awt.Color(255, 51, 51));
        jchkMRed.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMRed.setForeground(new java.awt.Color(255, 255, 255));
        jchkMRed.setText("100");
        jchkMRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMRed.setBorderPainted(true);
        jchkMRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMRedActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 110, -1));

        jchkMOrange.setBackground(new java.awt.Color(255, 153, 0));
        jchkMOrange.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMOrange.setForeground(new java.awt.Color(255, 255, 255));
        jchkMOrange.setText("1000");
        jchkMOrange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMOrange.setBorderPainted(true);
        jchkMOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMOrangeActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 110, -1));

        jchkMGray.setBackground(new java.awt.Color(102, 102, 102));
        jchkMGray.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMGray.setForeground(new java.awt.Color(255, 255, 255));
        jchkMGray.setText("100000000");
        jchkMGray.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMGray.setBorderPainted(true);
        jchkMGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMGrayActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMGray, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 110, 20));

        jchkMViolet.setBackground(new java.awt.Color(255, 51, 255));
        jchkMViolet.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMViolet.setForeground(new java.awt.Color(255, 255, 255));
        jchkMViolet.setText("10000000");
        jchkMViolet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMViolet.setBorderPainted(true);
        jchkMViolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMVioletActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMViolet, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 110, 20));

        jchkMBlue.setBackground(new java.awt.Color(0, 51, 204));
        jchkMBlue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMBlue.setForeground(new java.awt.Color(255, 255, 255));
        jchkMBlue.setText("1000000");
        jchkMBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMBlue.setBorderPainted(true);
        jchkMBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMBlueActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 110, 20));

        jchkMGreen.setBackground(new java.awt.Color(51, 204, 0));
        jchkMGreen.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMGreen.setForeground(new java.awt.Color(255, 255, 255));
        jchkMGreen.setText("100000");
        jchkMGreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMGreen.setBorderPainted(true);
        jchkMGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMGreenActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 110, 20));

        jchkMYellow.setBackground(new java.awt.Color(255, 255, 0));
        jchkMYellow.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMYellow.setText("10000");
        jchkMYellow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMYellow.setBorderPainted(true);
        jchkMYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMYellowActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 110, -1));

        jchkMBlack.setBackground(new java.awt.Color(0, 0, 0));
        jchkMBlack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jchkMBlack.setForeground(new java.awt.Color(255, 255, 255));
        jchkMBlack.setText("1");
        jchkMBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkMBlack.setBorderPainted(true);
        jchkMBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMBlackActionPerformed(evt);
            }
        });
        jPanel3.add(jchkMBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 110, -1));

        jchkNone.setText("               20%");
        jchkNone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkNone.setBorderPainted(true);
        jchkNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkNoneActionPerformed(evt);
            }
        });
        jPanel3.add(jchkNone, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 110, 20));

        jchkSliver.setBackground(new java.awt.Color(204, 204, 204));
        jchkSliver.setText("               10%");
        jchkSliver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkSliver.setBorderPainted(true);
        jchkSliver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSliverActionPerformed(evt);
            }
        });
        jPanel3.add(jchkSliver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 110, 20));

        jchkGold.setBackground(new java.awt.Color(255, 204, 153));
        jchkGold.setText("                5%");
        jchkGold.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jchkGold.setBorderPainted(true);
        jchkGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkGoldActionPerformed(evt);
            }
        });
        jPanel3.add(jchkGold, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 110, 20));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 180, 50));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 10));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jlblLine4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlblLine4.setOpaque(true);
        jPanel4.add(jlblLine4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 10, 50));

        jlblLine1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlblLine1.setOpaque(true);
        jPanel4.add(jlblLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 10, 50));

        jlblLine2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlblLine2.setOpaque(true);
        jPanel4.add(jlblLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 10, 50));

        jlblLine3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlblLine3.setOpaque(true);
        jPanel4.add(jlblLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 10, 50));

        jlblIndicator.setBackground(new java.awt.Color(0, 204, 204));
        jlblIndicator.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jlblIndicator.setForeground(new java.awt.Color(255, 255, 255));
        jlblIndicator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblIndicator.setText("Enter First Colour");
        jlblIndicator.setOpaque(true);
        jPanel4.add(jlblIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 300, 50));

        jLabel31.setBackground(new java.awt.Color(0, 204, 204));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Fist Colour Code");
        jLabel31.setOpaque(true);
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 210, 20));

        jlblSecondColour.setBackground(new java.awt.Color(0, 204, 204));
        jlblSecondColour.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblSecondColour.setForeground(new java.awt.Color(255, 255, 255));
        jlblSecondColour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSecondColour.setOpaque(true);
        jPanel4.add(jlblSecondColour, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 120, 20));

        jLabel33.setBackground(new java.awt.Color(0, 204, 204));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Second Colour Code");
        jLabel33.setOpaque(true);
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 210, 20));

        jlblMultiple.setBackground(new java.awt.Color(0, 204, 204));
        jlblMultiple.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblMultiple.setForeground(new java.awt.Color(255, 255, 255));
        jlblMultiple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMultiple.setOpaque(true);
        jPanel4.add(jlblMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 120, 20));

        jLabel35.setBackground(new java.awt.Color(0, 204, 204));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Multiplier");
        jLabel35.setOpaque(true);
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 210, 20));

        jlblFirstColour.setBackground(new java.awt.Color(0, 204, 204));
        jlblFirstColour.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblFirstColour.setForeground(new java.awt.Color(255, 255, 255));
        jlblFirstColour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblFirstColour.setOpaque(true);
        jPanel4.add(jlblFirstColour, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 120, 20));

        jLabel37.setBackground(new java.awt.Color(0, 204, 204));
        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Divide By 1000");
        jLabel37.setOpaque(true);
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 210, 20));

        jLabel38.setBackground(new java.awt.Color(0, 204, 204));
        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Resistor Value");
        jLabel38.setOpaque(true);
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 210, 20));

        jLabel39.setBackground(new java.awt.Color(0, 204, 204));
        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Minimum Range");
        jLabel39.setOpaque(true);
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 210, 20));

        jlblMinRange.setBackground(new java.awt.Color(0, 204, 204));
        jlblMinRange.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblMinRange.setForeground(new java.awt.Color(255, 255, 255));
        jlblMinRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMinRange.setOpaque(true);
        jPanel4.add(jlblMinRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 120, 20));

        jlblResistorValue.setBackground(new java.awt.Color(0, 204, 204));
        jlblResistorValue.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblResistorValue.setForeground(new java.awt.Color(255, 255, 255));
        jlblResistorValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblResistorValue.setOpaque(true);
        jPanel4.add(jlblResistorValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 120, 20));

        jlblDivideby1000.setBackground(new java.awt.Color(0, 204, 204));
        jlblDivideby1000.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblDivideby1000.setForeground(new java.awt.Color(255, 255, 255));
        jlblDivideby1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDivideby1000.setOpaque(true);
        jPanel4.add(jlblDivideby1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 120, 20));

        jlblMaxRange.setBackground(new java.awt.Color(0, 204, 204));
        jlblMaxRange.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblMaxRange.setForeground(new java.awt.Color(255, 255, 255));
        jlblMaxRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMaxRange.setOpaque(true);
        jPanel4.add(jlblMaxRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 120, 20));

        jLabel44.setBackground(new java.awt.Color(0, 204, 204));
        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Maximum Range");
        jLabel44.setOpaque(true);
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 210, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1340, 600));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EXITE RESISTOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CALCULATE RESISTOR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 732, 1340, 60));

        jLabel30.setBackground(new java.awt.Color(0, 204, 204));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 204, 204));
        jLabel30.setText("RESISTOR COLOUR CODE CALCULATOR");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 740, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jchkFBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFBlackActionPerformed
       jlblFirstColour.setText("0");
       jlblLine1.setBackground(Color.BLACK);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFBlackActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jchkFBlack.setOpaque(true);
        jchkFBrown.setOpaque(true);
        jchkFRed.setOpaque(true);
        jchkFOrange.setOpaque(true);
        jchkFYellow.setOpaque(true);
        jchkFGreen.setOpaque(true);
        jchkFBlue.setOpaque(true);
        jchkFViolet.setOpaque(true);
        jchkFGray.setOpaque(true);
        jchkFWhite.setOpaque(true);
        jchkGold.setOpaque(true);
        jchkSliver.setOpaque(true);
        jchkNone.setOpaque(true);
        
        jchkMBlack.setOpaque(true);
        jchkMBrown.setOpaque(true);
        jchkMRed.setOpaque(true);
        jchkMOrange.setOpaque(true);
        jchkMYellow.setOpaque(true);
        jchkMGreen.setOpaque(true);
        jchkMBlue.setOpaque(true);
        jchkMViolet.setOpaque(true);
        jchkMGray.setOpaque(true);
        jchkMWhite.setOpaque(true);
        
        
        jchkSBlack.setOpaque(true);
        jchkSBrown.setOpaque(true);
        jchkSRed.setOpaque(true);
        jchkSOrange.setOpaque(true);
        jchkSYellow.setOpaque(true);
        jchkSGreen.setOpaque(true);
        jchkSBlue.setOpaque(true);
        jchkSViolet.setOpaque(true);
        jchkSGray.setOpaque(true);
        jchkSWhite.setOpaque(true);
    }//GEN-LAST:event_formWindowActivated

    private void jchkFBrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFBrownActionPerformed
       jlblFirstColour.setText("1");
       jlblLine1.setBackground(Color.pink);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFBrownActionPerformed

    private void jchkFRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFRedActionPerformed
       jlblFirstColour.setText("2");
       jlblLine1.setBackground(Color.RED);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFRedActionPerformed

    private void jchkFOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFOrangeActionPerformed
        jlblMultiple.setText("3");
       jlblLine1.setBackground(Color.ORANGE);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFOrangeActionPerformed

    private void jchkFYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFYellowActionPerformed
        jlblFirstColour.setText("4");
       jlblLine1.setBackground(Color.YELLOW);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFYellowActionPerformed

    private void jchkFGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFGreenActionPerformed
        jlblFirstColour.setText("5");
       jlblLine1.setBackground(Color.GREEN);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFGreenActionPerformed

    private void jchkFBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFBlueActionPerformed
        jlblFirstColour.setText("6");
       jlblLine1.setBackground(Color.BLUE);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFBlueActionPerformed

    private void jchkFVioletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFVioletActionPerformed
       jlblFirstColour.setText("7");
       jlblLine1.setBackground(Color.MAGENTA);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFVioletActionPerformed

    private void jchkFGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFGrayActionPerformed
        jlblFirstColour.setText("8");
       jlblLine1.setBackground(Color.GRAY);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFGrayActionPerformed

    private void jchkFWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFWhiteActionPerformed
        jlblFirstColour.setText("9");
       jlblLine1.setBackground(Color.WHITE);
       jlblIndicator.setText("Select Second Colour");
    }//GEN-LAST:event_jchkFWhiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JCheckBox clearJCheckBox= null;
        for (Component c:jPanel3.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JCheckBox")){
                clearJCheckBox = (JCheckBox)c;
                clearJCheckBox.setSelected(false);
            }
        }
        
        
        
        jlblFirstColour.setText("");
        jlblSecondColour.setText("");
        jlblMultiple.setText("");
        jlblLine2.setBackground(Color.darkGray);
        jlblLine1.setBackground(Color.darkGray);
        jlblLine3.setBackground(Color.darkGray);
        jlblLine4.setBackground(Color.darkGray);

        jlblMinRange.setText("");
        jlblMaxRange.setText("");
        jlblIndicator.setText("");
       
        jlblResistorValue.setText("");
        
        jlblDivideby1000.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jchkSBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSBlackActionPerformed
       jlblSecondColour.setText("0");
       jlblLine2.setBackground(Color.BLACK);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSBlackActionPerformed

    private void jchkSBrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSBrownActionPerformed
        jlblSecondColour.setText("1");
       jlblLine2.setBackground(Color.pink);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSBrownActionPerformed

    private void jchkSRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSRedActionPerformed
       jlblSecondColour.setText("2");
       jlblLine2.setBackground(Color.RED);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSRedActionPerformed

    private void jchkSOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSOrangeActionPerformed
       jlblSecondColour.setText("3");
       jlblLine2.setBackground(Color.ORANGE);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSOrangeActionPerformed

    private void jchkSYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSYellowActionPerformed
        jlblSecondColour.setText("4");
       jlblLine2.setBackground(Color.YELLOW);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSYellowActionPerformed

    private void jchkSGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSGreenActionPerformed
        jlblSecondColour.setText("5");
       jlblLine2.setBackground(Color.GREEN);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSGreenActionPerformed

    private void jchkSBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSBlueActionPerformed
       jlblSecondColour.setText("6");
       jlblLine2.setBackground(Color.BLUE);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSBlueActionPerformed

    private void jchkSVioletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSVioletActionPerformed
       jlblSecondColour.setText("7");
       jlblLine2.setBackground(Color.MAGENTA);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSVioletActionPerformed

    private void jchkSGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSGrayActionPerformed
        jlblSecondColour.setText("8");
       jlblLine2.setBackground(Color.GRAY);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSGrayActionPerformed

    private void jchkSWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSWhiteActionPerformed
       jlblSecondColour.setText("9");
       jlblLine2.setBackground(Color.WHITE);
       jlblIndicator.setText("Select MULTIPLIER");
    }//GEN-LAST:event_jchkSWhiteActionPerformed

    private void jchkMBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMBlackActionPerformed
       jlblMultiple.setText("1");
       jlblLine3.setBackground(Color.BLACK);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMBlackActionPerformed

    private void jchkMBrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMBrownActionPerformed
        jlblMultiple.setText("10");
       jlblLine3.setBackground(Color.pink);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMBrownActionPerformed

    private void jchkMRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMRedActionPerformed
        jlblMultiple.setText("100");
       jlblLine3.setBackground(Color.RED);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMRedActionPerformed

    private void jchkMOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMOrangeActionPerformed
       jlblMultiple.setText("1000");
       jlblLine3.setBackground(Color.ORANGE);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMOrangeActionPerformed

    private void jchkMYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMYellowActionPerformed
        jlblMultiple.setText("10000");
       jlblLine3.setBackground(Color.YELLOW);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMYellowActionPerformed

    private void jchkMGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMGreenActionPerformed
        jlblMultiple.setText("100000");
       jlblLine3.setBackground(Color.GREEN);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMGreenActionPerformed

    private void jchkMBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMBlueActionPerformed
        jlblMultiple.setText("1000000");
       jlblLine3.setBackground(Color.BLUE);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMBlueActionPerformed

    private void jchkMVioletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMVioletActionPerformed
        jlblMultiple.setText("10000000");
       jlblLine3.setBackground(Color.MAGENTA);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMVioletActionPerformed

    private void jchkMGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMGrayActionPerformed
       jlblMultiple.setText("100000000");
       jlblLine3.setBackground(Color.GRAY);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMGrayActionPerformed

    private void jchkMWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMWhiteActionPerformed
       jlblMultiple.setText("1000000000");
       jlblLine3.setBackground(Color.WHITE);
       jlblIndicator.setText("Select a Tolerance");
    }//GEN-LAST:event_jchkMWhiteActionPerformed

    private void jchkGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkGoldActionPerformed
        jlblIndicator.setText("Click on Calculator Resistor");
        jlblLine4.setBackground(Color.orange);
    }//GEN-LAST:event_jchkGoldActionPerformed

    private void jchkSliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSliverActionPerformed
         jlblIndicator.setText("Click on Calculator Resistor");
        jlblLine4.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jchkSliverActionPerformed

    private void jchkNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkNoneActionPerformed
        jlblIndicator.setText("Click on Calculator Resistor");
        jlblLine4.setBackground(Color.white);
    }//GEN-LAST:event_jchkNoneActionPerformed

    private JFrame frame;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog( frame, "Confirm if you want to exit", "Resistor Colour Code Calculator",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double [] q = new double[8];
        
        String f = String.format(jlblFirstColour.getText());
        String s = String.format(jlblSecondColour.getText());
        
        double t = Double.parseDouble(jlblMultiple.getText());
        
        String fs = f + s;
        q[1] = Double.parseDouble(fs);
        q[2] = q[1];
        
        if(jchkGold.isSelected() == true){
            jlblResistorValue.setText(String.format((q[2]) + ("K ohm")));
            q[3] = (((q[2] * t) / 1000) * (0.050));
            String Divideby1000 = String.format("%.2f", q[3]);
            jlblDivideby1000.setText(Divideby1000);
            
            q[4] = (q[2]) - (q[3]);
            jlblMinRange.setText(String.format((q[4]) + ("K ohm") ));
            
            q[5] = (q[2]) + (q[3]);
            jlblMaxRange.setText(String.format((q[5]) + ("K ohm") ));
        }
        
        else if(jchkSliver.isSelected() == true){
            jlblResistorValue.setText(String.format((q[2]) + ("K ohm")));
            q[3] = (((q[2] * t) / 1000) * (0.1));
            String Divideby1000 = String.format("%.2f", q[3]);
            jlblDivideby1000.setText(Divideby1000);
            
            q[4] = (q[2]) - (q[3]);
            jlblMinRange.setText(String.format((q[4]) + ("K ohm") ));
            
            q[5] = (q[2]) + (q[3]);
            jlblMaxRange.setText(String.format((q[5]) + ("K ohm") ));
        }
        
        else if(jchkNone.isSelected() == true){
            jlblResistorValue.setText(String.format((q[2]) + ("K ohm")));
            q[3] = (((q[2] * t) / 1000) * (0.2));
            String Divideby1000 = String.format("%.2f", q[3]);
            jlblDivideby1000.setText(Divideby1000);
            
            q[4] = (q[2]) - (q[3]);
            jlblMinRange.setText(String.format((q[4]) + ("K ohm") ));
            
            q[5] = (q[2]) + (q[3]);
            jlblMaxRange.setText(String.format((q[5]) + ("K ohm") ));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colour_code_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colour_code_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colour_code_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colour_code_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colour_code_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JCheckBox jchkFBlack;
    private javax.swing.JCheckBox jchkFBlue;
    private javax.swing.JCheckBox jchkFBrown;
    private javax.swing.JCheckBox jchkFGray;
    private javax.swing.JCheckBox jchkFGreen;
    private javax.swing.JCheckBox jchkFOrange;
    private javax.swing.JCheckBox jchkFRed;
    private javax.swing.JCheckBox jchkFViolet;
    private javax.swing.JCheckBox jchkFWhite;
    private javax.swing.JCheckBox jchkFYellow;
    private javax.swing.JCheckBox jchkGold;
    private javax.swing.JCheckBox jchkMBlack;
    private javax.swing.JCheckBox jchkMBlue;
    private javax.swing.JCheckBox jchkMBrown;
    private javax.swing.JCheckBox jchkMGray;
    private javax.swing.JCheckBox jchkMGreen;
    private javax.swing.JCheckBox jchkMOrange;
    private javax.swing.JCheckBox jchkMRed;
    private javax.swing.JCheckBox jchkMViolet;
    private javax.swing.JCheckBox jchkMWhite;
    private javax.swing.JCheckBox jchkMYellow;
    private javax.swing.JCheckBox jchkNone;
    private javax.swing.JCheckBox jchkSBlack;
    private javax.swing.JCheckBox jchkSBlue;
    private javax.swing.JCheckBox jchkSBrown;
    private javax.swing.JCheckBox jchkSGray;
    private javax.swing.JCheckBox jchkSGreen;
    private javax.swing.JCheckBox jchkSOrange;
    private javax.swing.JCheckBox jchkSRed;
    private javax.swing.JCheckBox jchkSViolet;
    private javax.swing.JCheckBox jchkSWhite;
    private javax.swing.JCheckBox jchkSYellow;
    private javax.swing.JCheckBox jchkSliver;
    private javax.swing.JLabel jlblDivideby1000;
    private javax.swing.JLabel jlblFirstColour;
    private javax.swing.JLabel jlblIndicator;
    private javax.swing.JLabel jlblLine1;
    private javax.swing.JLabel jlblLine2;
    private javax.swing.JLabel jlblLine3;
    private javax.swing.JLabel jlblLine4;
    private javax.swing.JLabel jlblMaxRange;
    private javax.swing.JLabel jlblMinRange;
    private javax.swing.JLabel jlblMultiple;
    private javax.swing.JLabel jlblResistorValue;
    private javax.swing.JLabel jlblSecondColour;
    // End of variables declaration//GEN-END:variables
}
